[package]
name = "sumcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ark-bls12-381 = "0.4.0"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
ark-test-curves = "0.4.2"
